apiVersion: v1
kind: Service
metadata:
  name: dashboard-load-balancer
  namespace: sentiment-trading
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-xxxxxxxxx,subnet-yyyyyyyyy"
    service.beta.kubernetes.io/aws-load-balancer-security-groups: "sg-xxxxxxxxx"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "Project=sentiment-trading,Environment=production"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8501
      protocol: TCP
      name: http
    - port: 443
      targetPort: 8501
      protocol: TCP
      name: https
  selector:
    app: dashboard-service
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: sentiment-api-load-balancer
  namespace: sentiment-trading
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-xxxxxxxxx,subnet-yyyyyyyyy"
    service.beta.kubernetes.io/aws-load-balancer-security-groups: "sg-xxxxxxxxx"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8001
      protocol: TCP
      name: http
  selector:
    app: sentiment-service
---
apiVersion: v1
kind: Service
metadata:
  name: trading-api-load-balancer
  namespace: sentiment-trading
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-xxxxxxxxx,subnet-yyyyyyyyy"
    service.beta.kubernetes.io/aws-load-balancer-security-groups: "sg-xxxxxxxxx"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8002
      protocol: TCP
      name: http
  selector:
    app: trading-service
